### ISSUE TITLE
SQL error !

### ISSUE THREAD

**Issue by yinflying** [Franco-Poveda/node-cmd-stash#3]
```
$ stash list
{ Error: SQLITE_ERROR: no such table: state errno: 1, code: 'SQLITE_ERROR' }
/usr/lib/node_modules/command-stash/index.js:27
    const currpack = row.pack;
                        ^

TypeError: Cannot read property 'pack' of undefined
    at /usr/lib/node_modules/command-stash/index.js:27:25
    at Statement.errBack (/usr/lib/node_modules/command-stash/node_modules/_sqlite3@3.1.9@sqlite3/lib/sqlite3.js:16:21)
```
It seems that I should install SQLITE....but I check it:
```
$ pacman -Qs sqlite                                                                            
local/lib32-sqlite 3.19.3-1
    A C library that implements an SQL database engine (32-bit)
local/sqlite 3.20.0-1
    A C library that implements an SQL database engine
```
Is there anything wrong ?

**Comment by Franco-Poveda** [comment]
there is no need to install sqlite engine on your system.
Can you check if the file: /home/< user >/stash.db was created?
The package was installed with sudo?

**Comment by Franco-Poveda** [comment]
try running one more time: 

`cnpm install command-stash -g`

can you post your npm / cnpm error logs?

**Comment by yinflying** [comment]
I installed it with `sudo`, ok , it seems that I could create `~/stash.db` and work fine with command `sudo stash list`, 

however , what should I do without `sudo` ? It seems strange...

**Comment by Franco-Poveda** [comment]
Your problem seems to be that NPM/CNPM and NodeJS binaries, were installed originally with the need of super user privileges. This makes all global installations require sudo for execution and symbolic linking.
This link will help you with that:

[https://docs.npmjs.com/getting-started/fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

Its a common problem if you do not use `NVM` to manage your nodejs environments and binaries. 

Refer to: [https://github.com/creationix/nvm](https://github.com/creationix/nvm)

**If the binary "`stash`" can be executed without sudo, i think a fast workaround may be "`chmod`" the file `~/stash.db` so your ordinary user can `+rwx` it.**

Can you please post the error or screens captures! I'am just guessing here!

**Comment by Franco-Poveda** [comment]
The original error of the thread is because your user do not have permissions `rwx` to `stash.db`

**Comment by yinflying** [comment]
Thank you!
I have reinstall the npm (and cnpm) and set the prefix...Here is a solution:
```
# after reinstalled the npm .....
$ cd && mkdir npm-install
$ npm config set prefix '/home/xx/npm-install'
$ npm install -g command-stash
```
seems workfine ...

what's more , I find it both create `/root/stash.db` and `~/stash.db` after `sudo stash` , of course it only store the message to `/root/stash.db` ... 

Blame on the way I use the `npm`.... Thank you !
